### ISSUE TITLE
Why is there no data for suno songs on my webpage?

### ISSUE THREAD

**Issue by JasonKid-maker** [Sprheany/ai-song#1]
![微信图片_20240716150238](https://github.com/user-attachments/assets/10bc1680-5133-4240-bf0a-7739e3e382f0)
Why is there no data for suno songs on my webpage?

**Comment by Sprheany** [comment]
You should run `npm run db:seed` to crawl the musics, I've updated the README.

**Comment by JasonKid-maker** [comment]
![微信图片_20240717185031](https://github.com/user-attachments/assets/c202ae21-d3d9-4891-ab5b-b7e385aafc21)

@Sprheany Thank you for helping me solve the problem, but I still cannot generate music. I think this may be an issue with the suno API

**Comment by Sprheany** [comment]
I'm sorry I don't have time to deal with about this issue right now, the problem of not being able to generate music you can fix according to this project https://github.com/gcui-art/suno-api
